
#ifndef VTKTESTINGGENERICBRIDGE_EXPORT_H
#define VTKTESTINGGENERICBRIDGE_EXPORT_H

#ifdef VTKTESTINGGENERICBRIDGE_STATIC_DEFINE
#  define VTKTESTINGGENERICBRIDGE_EXPORT
#  define VTKTESTINGGENERICBRIDGE_NO_EXPORT
#else
#  ifndef VTKTESTINGGENERICBRIDGE_EXPORT
#    ifdef TestingGenericBridge_EXPORTS
        /* We are building this library */
#      define VTKTESTINGGENERICBRIDGE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKTESTINGGENERICBRIDGE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKTESTINGGENERICBRIDGE_NO_EXPORT
#    define VTKTESTINGGENERICBRIDGE_NO_EXPORT 
#  endif
#endif

#ifndef VTKTESTINGGENERICBRIDGE_DEPRECATED
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKTESTINGGENERICBRIDGE_DEPRECATED_EXPORT
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED_EXPORT VTKTESTINGGENERICBRIDGE_EXPORT VTKTESTINGGENERICBRIDGE_DEPRECATED
#endif

#ifndef VTKTESTINGGENERICBRIDGE_DEPRECATED_NO_EXPORT
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED_NO_EXPORT VTKTESTINGGENERICBRIDGE_NO_EXPORT VTKTESTINGGENERICBRIDGE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKTESTINGGENERICBRIDGE_NO_DEPRECATED
#    define VTKTESTINGGENERICBRIDGE_NO_DEPRECATED
#  endif
#endif

#endif /* VTKTESTINGGENERICBRIDGE_EXPORT_H */
